[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/users" # simple health check
healthcheckTimeout = 100
